### ISSUE TITLE
Issue with Sphinx "parallel reading"

### ISSUE THREAD

**Issue by GlenNicholls** [spacemanspiff2007/sphinx-exec-code#2]
I am running sphinx with the following command:

```
sphinx-build -nWT -b html -j auto docs build/docs/html
```

It looks like the `j` flag causes sphinx-exec-code to give the following warning:

```
Warning, treated as error:
the sphinx_exec_code extension does not declare if it is safe for parallel reading, assuming it isn't - please ask the extension author to check and make it explicit
```

For reference, I am running sphinx 4.4.0 and sphinx-exec-code 0.4

**Comment by spacemanspiff2007** [comment]
I've marked it accordingly in v0.5. Could you check if you experience any errors and report back? 
Thank you.

**Comment by GlenNicholls** [comment]
Awesome, thank you! I don't see this issue anymore.
