### ISSUE TITLE
Unicode support

### ISSUE THREAD

**Issue by rwijtvliet** [spacemanspiff2007/sphinx-exec-code#3]
`print("●")` works in python, but in sphinx, using

```
.. exec_code::

   print("●")
```

gives an ExtensionError:

```
ERROR:    print("●") <--
ERROR: 
ERROR: Traceback (most recent call last):
ERROR:   File "pfstate.rst", line 33
ERROR:   File "...\lib\encodings\cp1252.py", line 19, in encode
ERROR:     return codecs.charmap_encode(input,self.errors,encoding_table)[0]
ERROR: UnicodeEncodeError: 'charmap' codec can't encode character '\u25cf' in position 0: character maps to <undefined>

Extension error:
Could not execute code!
```

Let me know if there is more information I can provide.

--- 

It appears it's not the symbol in the source code, but rather the printing that is a problem, as this does work:

```
.. exec_code::

   print("●".replace("●", "circle"))
```

**Comment by spacemanspiff2007** [comment]
I can not reproduce the issue. What OS & Python Version are you running?

**Comment by rwijtvliet** [comment]
I'm on windows and python 3.8. If it's useful, I can also try on 3.9

**Comment by spacemanspiff2007** [comment]
Which windows version?

**Comment by rwijtvliet** [comment]
Edition	Windows 10 Enterprise
Version	21H2

**Comment by rwijtvliet** [comment]
Yes - same result:

```
.. exec_code::

   print("●")
```

```
building [html]: targets for 1 source files that are out of date
updating environment: 0 added, 1 changed, 0 removed
reading sources... [100%] core/pfstate
ERROR:    print("●") <--
ERROR: 
ERROR: Traceback (most recent call last):
ERROR:   File "pfstate.rst", line 7
ERROR:   File "...\lib\encodings\cp1252.py", line 19, in encode
ERROR:     return codecs.charmap_encode(input,self.errors,encoding_table)[0]
ERROR: UnicodeEncodeError: 'charmap' codec can't encode character '\u25cf' in position 0: character maps to <undefined>

Extension error:
Could not execute code!
Command exited with exit code: 2
The server will continue serving the build folder, but the contents being served are no longer in sync with the documentation sources. Please fix the cause of the error above or press Ctrl+C to stop the server.
```

Also, if that's relevant, I'm using Sphinx v5.0.2, and the output above is from `sphinx-autobuild`.

**Comment by spacemanspiff2007** [comment]
Could you please show the output of
```python
import sys
print(sys.stdout.encoding)
print(sys.stdin.encoding)
print(sys.getdefaultencoding())
```

**Comment by spacemanspiff2007** [comment]
You can set the encoding with 0.7 in the configuration

**Comment by rwijtvliet** [comment]
This is the output:

```
utf-8
utf-8

utf-8
cp1252
```

I'd never heard of this encoding, but according to wikipedia:

Windows-1252 or CP-1252 ([code page](https://en.wikipedia.org/wiki/Code_page) 1252) is a single-byte [character encoding](https://en.wikipedia.org/wiki/Character_encoding) of the [Latin alphabet](https://en.wikipedia.org/wiki/Latin_alphabet), used by default in the [legacy](https://en.wikipedia.org/wiki/Legacy_system) components of [Microsoft Windows](https://en.wikipedia.org/wiki/Microsoft_Windows) for English and many European languages including Spanish, French, and German.

It is the most-used single-byte character encoding in the world (on [websites](https://en.wikipedia.org/wiki/Website) at least). 

(...)

Depending on the country, (...), e.g. for Germany, according to website use (including ISO-8859-1) at 4.6%.[[6]](https://en.wikipedia.org/wiki/Windows-1252#cite_note-6)[[7]](https://en.wikipedia.org/wiki/Windows-1252#cite_note-7)

---

I happen to be in Germany, on a German-language system.

I'll have a look if I can change things on my machine - but it might also be something you want to have a look into? Not sure if it's worth the effort though.

**Comment by spacemanspiff2007** [comment]
You can set the encoding to utf-8 through the new config option in 0.7.
That should make the error disappear.

**Comment by rwijtvliet** [comment]
Hmm. I did the following:

* Updated to 0.7:

```
>>> import sphinx_exec_code
>>> sphinx_exec_code.__version__
'0.7'
```

* Added the line `exec_code_stdout_encoding = "utf-8"` to sphinx' `conf.py`.

However, I'm still getting the same error message:

```
ERROR:    print("●") <--
ERROR: 
ERROR: Traceback (most recent call last):
ERROR:   File "index.rst", line 84
ERROR:   File "C:\Users\ruud.wijtvliet\Anaconda3\envs\pf38\lib\encodings\cp1252.py", line 19, in encode
ERROR:     return codecs.charmap_encode(input,self.errors,encoding_table)[0]
ERROR: UnicodeEncodeError: 'charmap' codec can't encode character '\u25cf' in position 0: character maps to <undefined>
```

I tried both python 3.8 and 3.10.

Thanks for being so responsive btw; much appreciated.

**Comment by spacemanspiff2007** [comment]
could you try with 0.8.
Be aware that the parameter name has changed but the default should be okay for you.

**Comment by rwijtvliet** [comment]
I'm afraid it's still not working... 

I updated to 0.8 and removed the parameter in `conf.py`. 

Same error (Encoding Error).

Explicitly setting the new parameter to `True` in `conf.py` does not resolve the issue.

**Comment by spacemanspiff2007** [comment]
You could try some env vars to modify the behavior. ``exec-code`` inherits directly from the parent process so you can set the env vars for your sphinx build. There are some that specify [windows behavior](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONUTF8) - maybe that'll help?

**Comment by rwijtvliet** [comment]
Incredible, that solved it. Many thanks!!
