### ISSUE TITLE
Can't use :filename: directive after any code

### ISSUE THREAD

**Issue by mbopfNIH** [spacemanspiff2007/sphinx-exec-code#5]
I need to set an environment variable before I include using exec_code. The following works just fine:

```
.. exec_code::
   :filename: /tmp/file.py
```

However, any code included before the :filename: directive causes errors:

```
.. exec_code::

   print('here')
   :filename: /tmp/file.py
```

ERROR:    print('here')
ERROR:    :filename: /tmp/file.py
ERROR:    
ERROR:    
ERROR:    
ERROR:   File "<string>", line 3
ERROR:     :filename: /tmp/file.py
ERROR:     ^
ERROR: SyntaxError: invalid syntax

Extension error:
Could not execute code!
make: *** [html] Error 2

If I leave out the blank line, the :filename: include runs, but the print('here') line is ignored.

Is there anyway to execute some code before including a file?

**Comment by spacemanspiff2007** [comment]
It's either file or sphinx code but you can use code Markers to achieve everything.
